import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {NavBar} from "@/components/ui/NavBar";
import {auth} from "@/auth";
import {Toaster} from "@/components/ui/toaster";
import React from "react";

const fontSans = Inter({subsets: ["latin"], variable: "--font-sans"});
// @ts-ignore
export {fontSans};
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en">
		<body className={fontSans.className}>
		<ThemeProvider
			attribute="class"
			defaultTheme="system"
			enableSystem
			disableTransitionOnChange
		>
			<NavBar/>
			{children}
			<Toaster/>
		</ThemeProvider>
		</body>
		</html>
	);
}
